name: Nightly

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of Rethink Firewall to test: v055b'
        default: latest
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Version tag of Rethink Firewall to test: v055b'
        default: latest
        required: false
        type: string

permissions:
  contents: write

jobs:
  evaluateChanges:
    name: Evaluate changes for run or skipping nightly build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1



  build:
    name: Generate Nightly Build
    runs-on: ubuntu-latest
    env:
      SCHEDULED_BUILD_VARIANT: ${{ vars.SCHEDULED_BUILD_VARIANT }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and send apks to github
        run: |
          for TASK in $SCHEDULED_BUILD_VARIANT; do
            ./gradlew $TASK
            apk_path="$(find . -type f -iname *.apk)"
            echo $apk_path
          done
          
      - uses: actions/upload-artifact@v3
        with:
          name: RethinkApp-${{ inputs.version }}
          path: $apk_path
